PACKAGE_NAME="smitdtmb"
PACKAGE_VERSION="0.1"
CLEAN="make clean KVERSION=$kernelver LLVM=1 CC=clang"
MAKE[0]="make all KVERSION=$kernelver LLVM=1 CC=clang"
BUILT_MODULE_NAME[0]="smitdtmb"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
